language: android
sudo: false
jdk:
    - oraclejdk8
before_install:
    - yes | sdkmanager "platforms;android-30"
android:
    components:
        - build-tools-29.0.2
        - android-30
        - extra-android-m2repository
script:
    - cd BlinkIDSample
    - ./gradlew clean :BlinkID_AllRecognizersSample:assembleRelease
    - ./gradlew clean :BlinkID-CustomUISample:assembleRelease
    - ./gradlew clean :BlinkID-DirectApiSample:assembleRelease
    - ./gradlew clean :BlinkID-ImagesSample:assembleRelease
    - ./gradlew clean :BlinkID-CustomCombinedSample:assembleRelease
    - ./gradlew clean :BlinkID-aMinimalSample:assembleRelease
    - ./gradlew clean :BlinkID-OverlaySample:assembleRelease
